# Generated by Django 5.2.3 on 2025-06-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileSystemTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="FHS Tree", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seed", models.IntegerField(default=0)),
                ("mole_location", models.CharField(blank=True, max_length=500)),
                ("player_location", models.CharField(default="/home", max_length=500)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("tree_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(default="Anonymous", max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("commands_used", models.IntegerField(default=0)),
                ("directories_visited", models.IntegerField(default=0)),
                ("time_taken", models.DurationField(blank=True, null=True)),
                ("command_history", models.JSONField(default=list)),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="trees.filesystemtree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectoryNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("is_fhs_standard", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="trees.directorynode",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="trees.filesystemtree",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "unique_together": {("tree", "path")},
            },
        ),
    ]
