# Generated by Django 5.2.3 on 2025-06-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesystemtree",
            name="directory_stack",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="home_directory",
            field=models.CharField(default="/home", max_length=500),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="previous_location",
            field=models.CharField(default="", max_length=500),
        ),
    ]
