# Generated by Django 5.2.3 on 2025-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_filesystemtree_directory_stack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesystemtree",
            name="active_moles",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="difficulty_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="game_mode",
            field=models.CharField(default="single", max_length=20),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="max_moles_percentage",
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="mole_spawn_interval",
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="mole_type_weights",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="next_mole_spawn",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="moles_caught",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="moles_escaped",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
