# Generated by Django 5.2.3 on 2025-06-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0003_filesystemtree_active_moles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesystemtree",
            name="active_moles",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="game_mode",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="max_moles_percentage",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="mole_spawn_interval",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="mole_type_weights",
        ),
        migrations.RemoveField(
            model_name="filesystemtree",
            name="next_mole_spawn",
        ),
        migrations.RemoveField(
            model_name="gamesession",
            name="moles_caught",
        ),
        migrations.RemoveField(
            model_name="gamesession",
            name="moles_escaped",
        ),
        migrations.RemoveField(
            model_name="gamesession",
            name="score",
        ),
    ]
