# Generated by Django 5.2.3 on 2025-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0004_remove_filesystemtree_active_moles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesystemtree",
            name="moles_killed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="total_commands",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filesystemtree",
            name="total_directories_visited",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="mole_stats",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="moles_killed",
            field=models.IntegerField(default=0),
        ),
    ]
